
services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: intake_bot
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
